sudo: false
dist: trusty
language: perl
cache:
  directories:
  - extlib
perl:
- "5.30"
addons:
  apt:
    packages:
    - irssi
    - tree
    - libwww-perl
    - libyaml-perl
    - libhtml-parser-perl
    - libjson-pp-perl
before_install:
- git clone -q -b selfcheck_tmp https://github.com/bw1/scripts.irssi.org.git
install:
- cpanm --quiet LWP::UserAgent
- cpanm --quiet LWP::Protocol::https
- cpanm --quiet File::Slurper
- cpanm --quiet YAML
- 'echo $PWD'
before_script:
- 'echo $PWD'
  #- 'tree ~'
script:
- perl runselfcheck.pl
after_script:
- 'echo $PWD'
branches:
  only:
  - master

