sudo: false
dist: trusty
language: perl
cache:
  directories:
  - extlib
perl:
- "5.24-shrplib"
addons:
  apt:
    packages:
    - irssi
    - tree
    - libfile-slurper-perl
    - libyaml-perl
    - libwp-protocol-https-perl
    - libhtml-parser-perl
    - libjson-pp-perl
before_install:
- git clone -q -b chansearch2 https://github.com/bw1/scripts.irssi.org.git
install:
- 'echo $PWD'
before_script:
- 'tree ~'
script:
- perl runselfcheck.pl
after_script:
- cat tmp/info.yaml
branches:
  only:
  - master

