sudo: true
dist: bionic
#dist: Focal
#language: perl
language: Generic
#cache:
#  directories:
#  - extlib
#perl:
#- "5.26"
addons:
  apt:
    packages:
    - irssi
    - tree
    - cpanminus
    - libwww-perl
    - libyaml-perl
    - libyaml-libyaml-perl
    - libhtml-parser-perl
    - libjson-pp-perl
    - libxml-libxml-perl
    - libxml-simple-perl
    - libperl-prereqscanner-perl
    - libtest-fatal-perl
    - libfile-slurper-perl
before_install:
  #- sudo cpanm --quiet LWP::UserAgent
  #- sudo cpanm --quiet LWP::Protocol::https
  #- sudo cpanm --quiet YAML
  #- sudo cpanm --quiet File::Slurper
  #- sudo cpanm --quiet Perl::PrereqScanner
- sudo cpanm --quiet Module::Info
  #- sudo cpanm --quiet XML::LibXML::Simple
  #- sudo cpanm --quiet YAML::XS
install:
- git clone -b selfcheck_tmp https://github.com/bw1/scripts.irssi.org.git
- perl ModScanner.pl
- 'echo $PWD'
before_script:
- 'echo $PWD'
- bash -ev init_ontv.sh
  #- 'tree ~'
script:
- perl runselfcheck.pl
after_script:
- 'echo $PWD'
branches:
  only:
  - master

