name: check

on: 
  push:
  schedule:
     - cron: '0 12 * * 0'

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@master
    - name: pwd
      run: 'echo pwd: $PWD'
    - name: installpkg
      run: './rungetpkg.sh'
    - name: tree
      run: 'tree $PWD'
    - name: scripts
      run: git clone -b chansearch2 https://github.com/bw1/scripts.irssi.org.git
    - name: check scripts
      run: perl runselfcheck.pl
        #    - name: tree
        #      run: 'tree $PWD'
        #    - name: out info
        #      run: cat tmp/info.yaml
        #    - name: out log
        #      run: cat tmp/selfcheck.log
